CREATE DATABASE SPNote
GO	
USE SPNote
GO
CREATE TABLE dbo.Note
(
ID INT PRIMARY KEY,
Title NVARCHAR(200) NULL,
Descriptions NVARCHAR(MAX) NULL,
Modified DATETIME,
IsTrash BIT,
IsPin BIT
)
CREATE TABLE dbo.Tag
(
Tags NVARCHAR(200) PRIMARY KEY
)
CREATE TABLE dbo.TagNotes
(
Tag_Tags NVARCHAR(200),
Note_ID INT,
PRIMARY KEY(Tag_Tags,Note_ID),
FOREIGN KEY (Tag_Tags) REFERENCES dbo.Tag(Tags),
FOREIGN KEY(Note_ID) REFERENCES dbo.Note(ID)
)