//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleNoteeeeeeeeeeeee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<bool> IsPin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
        public override string ToString()
        {
            return Title;
        }
    }
}
